name: event_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  loading_overlay: ^0.3.0
  rflutter_alert: ^2.0.7
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  google_maps_flutter: ^2.6.1
  url_launcher: ^6.2.6
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.0
  location: ^6.0.1
  firebase_storage: ^11.7.4
  permission_handler: ^11.3.1
  flutter_image_compress: ^2.2.0
  progress_dialog_null_safe: ^3.0.0
  provider: ^6.1.2
  carousel_slider: ^4.2.1
  firebase_messaging: ^14.9.2
  http: ^1.2.1
  flutter_local_notifications: ^17.1.2
  rxdart_ext: ^0.2.9
  rxdart: ^0.27.5
  path_provider: ^2.1.3
  custom_rating_bar: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf